### ISSUE TITLE
Wrong result for sum((1-x)^(2*i), i, 0, n)

### ISSUE THREAD

**Issue by jbrea** [chakravala/Reduce.jl#7] opened 2018-03-27 14:15 UTC
```julia
julia> rcall(:(sum((1-x)^(2*i), i, 0, n)))
:((-((x - 1) ^ (2n)) * (x - 1) ^ 1) // ((x - 2) * x))
```
The result should be something like
```julia
:((((x - 1) ^ (2n)) * (x - 1) ^ 2 - 1) // ((x - 2) * x))
```

**Comment by chakravala** [comment] 2018-03-27 14:56
Thanks for finding this bug. It's an issue with the parser, when translating the `RExpr` into an `Expr`. I will investigate the cause of this issue as soon as am able to. The parser has grown much in complexity, although I spent a large amount of time looking for bugs, this is one I didn't come across before yet.

**Comment by chakravala** [comment] 2018-03-27 19:18
Okay, so I figured out where the problem comes from.

The temporary immediate fix is for you to to set
```Julia
Reduce.SubCall(false)
```
and then the expression will be correctly translated.
```Julia
julia> R"(-x+1)**(2*n)*(x-1)**2-1" |> parse
:((-x + 1) ^ (2n) * (x - 1) ^ 2 - 1)
```
However, I will fully fix the problem so that this option is not required. The expression `R"(-x+1)**(2*n)*(x-1)**2-1"` is split up by the parser into `"(-x+1)**(2*n)"` and `"(x-1)**2-1"` and then `RSymReplace` is called on each part to substitute the REDUCE operators with Julia operators. The problem is that if `SubCall` is enabled, then the substitution is carried out using a call to REDUCE, so `(x-1)**2-1"` gets simplified in this way:
```Julia
julia> Reduce._subst(Reduce.symrjl,"-1+(x+1)**2")
"(x + 2)*x"
```
This is technically correct for that subexpression; however this does not take into account that this term actually has another term that is multiplied on the left.

This can be fixed in the `RSymReplace` function, it will just need some extra parsing steps to further split the statement up into smaller pieces, so that each term is substituted separately.

**Comment by chakravala** [comment] 2018-03-27 21:22
Alrighty, this bug is now fixed on `master`, so everything should work fine now:
```Julia
julia> rcall(:(sum((1-x)^(2*i), i, 0, n)))
:(((-x + 1) ^ (2n) * (x - 1) ^ 2 - 1) // ((x - 2) * x))

julia> sum(:((1-x)^(2*i)), :i, 0, :n)
:(((-x + 1) ^ (2n) * (x - 1) ^ 2 - 1) // ((x - 2) * x))
```
Also, I have imported the `sum` function so that you can use it as `sum(::Expr, ...)` instead of having to use `rcall` to evaluate the sum.

It only required a change where a call to `_subst` is now handled by a new function
```Julia
function SubReplace(sym::String,str::String)
    a = matchall(r"([^ ()+*\^\/-]+|[()+*\^\/-])",str)
    for s ∈ 1:length(a)
        !isinfix(a[s]) && (a[s] ∉ ["(",")"]) && (a[s] = _subst(sym,a[s]))
    end
    return join(a)
end
```

It is on commit https://github.com/chakravala/Reduce.jl/commit/be480a2483fb6e1156b639631b08e28162de3a25, which will be part of the upcoming `v0.3.1` release.

Thanks for your bug report, hope everything else works fine for you.

**Closed by chakravala** 2018-03-27 21:22 UTC

**Comment by jbrea** [comment] 2018-03-27 21:32
Great. Thanks much for this super quick fix. I was using the package for the first time today. Looks very promising.
